<?php
$items      = ($block->getItems() AND $block->getItems() > 1) ? $block->getItems() : 1;
$nav        = $block->getShowNav() ? 'true' : 'false';
$loop       = $block->getLoop() ? 'true' : 'false';
$autoHeight = $block->getAutoHeight() ? 'true' : 'false';
?>

<?php if ($block->getSliders()) :?>
<div>
	<div class="mp-owl-carousel owl-carousel">
		<?php foreach ($block->getSliders() as $slider): ?>
			<?php $url = $slider->getUrl() ? $slider->getUrl() : '#'?>
			<div class="item"><a href="<?php echo $url ; ?>"><img src="<?php echo $slider->getBannerUrl(); ?>" alt="img"></a></div>
		<?php endforeach; ?>
	</div>
</div>
<script>// <![CDATA[
	require([
		'jquery',
        'Mageplaza_Productslider/js/owl.carousel.min'
	], function ($) {
		$(document).ready(function () {
			$(".mp-owl-carousel").owlCarousel({
				nav: <?php echo $nav;?>,
				items: <?php echo $items;?>,
				loop: 1,
				autoHeight: <?php echo $autoHeight;?>,
                autoplay: 1
			});
		});
	});
	// ]]></script>
<?php endif;?>
